version: '3'           #该docker-compose.yml文件使用的版本是 3
services:
  #vue-admin
  vue-admin:
    build: ./              #指定Dockerfile文件
    restart: always
    image: bmjlinecloud/vue-admin:v1              # 镜像名称:版本
    container_name: bmjlinecloud_vueadmin
    environment:
      TZ: Asia/Shanghai
    volumes: #挂载数据卷，同步主机与容器的配置文件
      - /data/bmjline/admin/dist:/usr/share/nginx/html
      - /data/bmjline/admin/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /data/bmjline/admin/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /data/bmjline/admin/log:/var/log/nginx
    ports:
      - "3000:80"                     #指定端口映射
